#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Preform one time setup
  sudo apt-get update
  sudo apt-get install apt-transport-https
  sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  # Install the Dart SDK:
  sudo apt-get update
  sudo apt-get install dart
elif [[ "$OSTYPE" == "darwin"* ]]; then
  brew tap dart-lang/dart
  brew install dart
fi

# Get CLI tools
pub global activate webdev

# Get dependencies
pub get

# Build the Server
webdev serve
